### ISSUE TITLE
Input names are non descriptive

### ISSUE THREAD

**Issue by kipplesunderscore** [kipplesunderscore/game#4]
Currently the input action names in the Godot project settings are things like `ui_accept` `ui_left` etc.
These should be changed to more descriptive names to improve code legibility.

Changing the Input Map in the project settings will break code so would need to update the names in the project settings and in the various code files.

**Comment by schneediener** [comment]
All custom input maps are now named more appropriate names that align with their general use-case. Updated code and tested game working OK, can score points, pick-up/put-down and jump.
