### ISSUE TITLE
Sound doesn't play during paused settings

### ISSUE THREAD

**Issue by schneediener** [kipplesunderscore/game#7]
I know how I want to fix this issue (trigger SFX/Music so long as the slider is held), but I just want to quickly know where you're triggering the jump sound effect, in the code/config. I can't find it in the code of the character

Best way I could find to message you is through an issue so here it is. If there is an easier way for me to comment/message let me know @kipplesunderscore

**Comment by kipplesunderscore** [comment]
In the player scene under the AnimationPlayer both the `jump_right` `jump_left` animations have the SFX
